### ISSUE TITLE
Error while converting files

### ISSUE THREAD

**Issue by JonasJasas** [ConvertAPI/convertapi-python#14]
Getting `requests.exceptions.HTTPError: 500 Server Error` for pptx to png conversion. Files are successfully converted using web interface https://www.convertapi.com/pptx-to-png

To reproduce: https://repl.it/@ConvertAPI/error

**Comment by tomasr78** [comment]
It seems the problem was related to TimeOut. First of all, there was a bug in ConvertAPI where **TimeOut** reported as **Conversion Fail.**. This is fixed and we deploying the new version.  The second issue that we have a very small timeout by default and it makes no sense to have only 180 seconds. The code below converts the file fine. I will post a new issue about the default timeout change.

import convertapi
import os
import tempfile

convertapi.api_secret = 'xxxx'

png_result = convertapi.convert(
    'png',
    {
        'File': 'test.pptx'
    }, 'pptx', 300
)

saved_files = png_result.save_files('./')

print("The thumbnail saved to %s" % saved_files)

**Comment by tomasr78** [comment]
I am closing this issue.
